In [1]:
import astropy.io.fits as pyfits
import numpy as np

### FSPS templates

In [2]:
file = pyfits.open('/Users/philipp/Documents/PhD/lum_func_measurement/templates/fsps_full/'
                'tweak_fsps_QSF_12_v3.param.fits')

In [3]:
print(file[1].header)

XTENSION= 'BINTABLE'           / binary table extension                         BITPIX  =                    8 / array data type                                NAXIS   =                    2 / number of array dimensions                     NAXIS1  =                  176 / length of dimension 1                          NAXIS2  =                   12 / length of dimension 2                          PCOUNT  =                    0 / number of group parameters                     GCOUNT  =                    1 / number of groups                               TFIELDS =                   22 / number of table fields                         TTYPE1  = 'Av      '                                                            TFORM1  = 'D       '                                                            TTYPE2  = 'mass    '                                                            TFORM2  = 'D       '                                                            TTYPE3  = 'Lv      '                    

### K-correct coefficients

In [4]:
kcorrect_will = pyfits.open('/Users/philipp/Downloads/eazy_files/cosmos2020_kcorr_coeffs_rerun.fits')

In [5]:
print(kcorrect_will[1].header)

XTENSION= 'BINTABLE'           / binary table extension                         BITPIX  =                    8 / array data type                                NAXIS   =                    2 / number of array dimensions                     NAXIS1  =                   36 / length of dimension 1                          NAXIS2  =               723897 / length of dimension 2                          PCOUNT  =                    0 / number of group parameters                     GCOUNT  =                    1 / number of groups                               TFIELDS =                    4 / number of table fields                         TTYPE1  = 'ID      '                                                            TFORM1  = 'K       '                                                            TTYPE2  = 'photoz  '                                                            TFORM2  = 'E       '                                                            TTYPE3  = 'z_eval  '                    

In [6]:
print(kcorrect_will[1].data['coeffs'])

[[3.9454789e-38 1.8039849e-02 1.1059473e-01 1.4621486e-07 4.1453216e-02]
 [0.0000000e+00 9.5163114e-02 4.7115239e-04 1.2297523e-26 2.9562911e-01]
 [1.0952668e-06 4.4133052e-02 3.2608914e-01 1.2349177e-02 1.7430569e-03]
 ...
 [5.8031276e-02 4.8697996e-01 1.0655838e+00 5.7400382e-01 9.8974973e-01]
 [3.7607069e+00 1.0022697e-04 6.1249930e-01 7.3060593e+01 2.0929125e-04]
 [7.2560372e+00 5.7178640e+00 4.9953568e+01 1.9266237e+01 7.2611241e+00]]


### Cosmos Catalogue Will

In [7]:
cosmos = pyfits.open('/Users/philipp/Downloads/eazy_files/COSMOS2020_Classic_processed.fits')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/philipp/Downloads/eazy_files/COSMOS2020_Classic_processed.fits'